Error: The automated vehicle type 'blub' of vehicle 'ToC_veh' is not known.
Quitting (on error).
Traceback (most recent call last):
  File "/home/micha/programming/sumo/tests/../tests/complex/sumo/ToCDevice/invalid_vType_param/runner.py", line 47, in <module>
    traci.start([sumoBinary, "-n", "input_net.net.xml", "-r", "input_routes.rou.xml", "--no-step-log", "true"])
  File "/home/micha/sumo/tools/traci/main.py", line 147, in start
    result = init(sumoPort, numRetries, "localhost", label, sumoProcess, doSwitch, traceFile, traceGetters)
  File "/home/micha/sumo/tools/traci/main.py", line 119, in init
    return con.getVersion()
  File "/home/micha/sumo/tools/traci/connection.py", line 382, in getVersion
    result = self._sendCmd(command, None, None)
  File "/home/micha/sumo/tools/traci/connection.py", line 231, in _sendCmd
    return self._sendExact()
  File "/home/micha/sumo/tools/traci/connection.py", line 137, in _sendExact
    raise FatalTraCIError("Connection closed by SUMO.")
traci.exceptions.FatalTraCIError: Connection closed by SUMO.
